<h1>hello</h1>
<div class="test">
	<button id="show_hide">Menu</button><br><br><br><br>
	<ul class="menu" style="display: none">
			<li>
				<a id="home" style="cursor: pointer;">Home</a>
				<div id="ul" style="display: none;">
					<ul>
						<li><a href="#">Men</a></li>
						<li><a href="#">Women</a></li>
					</ul>
				</div>
			</li>
			<li><a href="#">Products</a></li>
			<li><a href="#">Services</a></li>
			<li><a href="#">About</a></li>
			<li><a href="#">Contact</a></li>
	</ul>
</div>